agridata:
  tvd-equid-owner-dropdown:
    enabled: true
quarkus:
  http:
    test-timeout: 60s
  console:
    color: true
  cxf:
    client:
      uid:
        http-conduit-factory: URLConnectionHTTPConduitFactory
        client-endpoint-url: http://localhost:8051/uid-register/findByUid
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/testdata
  keycloak:
    devservices:
      realm-path: agate_realm.json
  log:
    level: WARN
    category:
      ch.agridata.common.filters:
        level: WARN
  oidc-client:
    agis-api:
      token-path: http://localhost:8051/agate/token
  rest-client:
    agis-register-api:
      url: http://localhost:8051/agis/register-data/1
    agis-structure-api:
      url: http://localhost:8051/agis/structure-data/1
    agis-eco-etho-api:
      url: http://localhost:8051/agis/eco-etho-data/1
    tvd-animal-tracing-api:
      url: http://localhost:8051/tvd/animal-tracing/v1.0
  wiremock:
    devservices:
      enabled: true
      files-mapping: src/test/resources/wiremock
      port: 8051
      reload: true
