on:
  workflow_call:
    inputs:
      account-id:
        required: true
        type: string
      ecr-repository-name:
        required: true
        type: string
      version:
        required: true
        type: string
        description: "Version tag for the Docker image"
    outputs:
      image:
        value: ${{ jobs.build-push-image.outputs.image }}

jobs:
  build-push-image:
    name: Build and push docker image
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      image: ${{ steps.push-image.outputs.image }}
    env:
      AWS_REGION: eu-central-2
      ECR_REPOSITORY: ${{inputs.ecr-repository-name}}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ format('v{0}', inputs.version) }}

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Restore Maven Cache
        uses: actions/cache/restore@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ needs.checkstyle.outputs.cache-date }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ needs.checkstyle.outputs.cache-date }}
            ${{ runner.os }}-maven-

      - name: Maven package
        run: mvn -B clean package -DskipTests -T 1C

      - name: Set image tag to GITHUB_ENV
        run: echo "IMAGE_TAG=${{ inputs.version }}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::${{inputs.account-id}}:role/agridata-application-deployment-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Tag Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

      - name: Push Image to AWS ECR
        id: push-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "IMAGE=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
