on:
  workflow_call:

jobs:
  owasp-dependency-check:
    name: OWASP Dependency Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Get Date for OWASP Cache
        id: get-cache-date
        run: |
          echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
        shell: bash

      - name: Restore Maven Cache
        uses: actions/cache/restore@v5
        with:
          path: ~/.m2/repository
          # Using date in cache key as OWASP database may change, without the pom changing
          key: ${{ runner.os }}-owasp-${{ steps.get-cache-date.outputs.date }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-owasp-${{ steps.get-cache-date.outputs.date }}
            ${{ runner.os }}-owasp-

      - name: Run OWASP Dependency Check
        run: |
          mvn org.owasp:dependency-check-maven:check \
            -DossindexAnalyzerEnabled=false \
            -DnvdApiKey=${{ secrets.API_KEY_NATIONAL_VULNERABILITY_DATABASE }} 

      - name: Save Maven Cache
        uses: actions/cache/save@v5
        if: always()
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-owasp-${{ steps.get-cache-date.outputs.date }}-${{ hashFiles('**/pom.xml') }}
