on:
  workflow_call:

jobs:
  unit-test-sonarqube:
    name: Unit Tests and SonarQube
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Restore Maven Cache
        uses: actions/cache/restore@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Unit Tests
        run: mvn -B test -T 1C

      - name: Run SonarQube Analysis
        run: |
          mvn -T 1C org.sonarsource.scanner.maven:sonar-maven-plugin:5.1.0.4751:sonar \
            -Dsonar.token=${{secrets.SONAR_TOKEN}} \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=agridata-ch \
            -Dsonar.projectKey=agridata-ch_backend \
            -Dsonar.sources=src/main/java \
            -Dsonar.test=src/test/java \
            -Dsonar.java.codeCoveragePlugin=jacoco \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/jacoco-report/jacoco.xml \
            -Dsonar.exclusions=**/agridata/common/openapi/**,**/agridata/testdata/**

      - name: Save Maven Cache
        uses: actions/cache/save@v4
        if: always()
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
